modLoader = "javafml"
loaderVersion = "[44,)"
license = "All rights reserved"

[[mods]]
modId = "forgednetworking"
version = "${version}"
displayName = "ForgedNetworkingAPI"
displayURL="https://github.com/ThinkingStudios/ForgedNetworkingAPI" #optional
logoFile="icon.png" #optional
credits="FabricMC" #optional
authors="ThinkingStudio" #optional
description = '''
Fabric API's Networking forge port.

Low-level, vanilla protocol oriented networking hooks.
'''

[[dependencies.forgednetworking]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forgednetworking]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.3,1.20.4)"
ordering = "NONE"
side = "BOTH"
