modLoader = "javafml"
loaderVersion = "[1,)"
license = "Apache-2.0"

[[mods]]
modId = "forged_networking"
version = "${version}"
displayName = "ForgedNetworkingAPI"
displayURL="https://github.com/ThinkingStudios/ForgedNetworkingAPI" #optional
logoFile="icon.png" #optional
credits="FabricMC" #optional
authors="ThinkingStudio" #optional
description = '''
Fabric API's Networking forge port.

Low-level, vanilla protocol oriented networking hooks.
'''

[[mixins]]
config = "forged-networking-api.mixins.json"

[[dependencies.forged_networking]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forged_networking]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.3,)"
ordering = "NONE"
side = "BOTH"
